# Copyright 2026 FlagOS Contributors
# Licensed under the Apache License, Version 2.0.

"""Validate prepared packages without importing torch or loading device libraries."""

import argparse
import base64
import csv
import hashlib
import io
import sys
import zipfile
import zlib
from pathlib import Path


def check_record(rows, read_file, required, allow_bytecode=False):
    verified = set()
    for name, digest, size in rows:
        if not name.startswith(required):
            continue
        # pip adds locally generated bytecode to an installed RECORD without
        # hashes. Validate the source files instead; bytecode is regenerable.
        if allow_bytecode and name.endswith(".pyc") and not digest:
            continue
        if not digest:
            raise ValueError(f"Missing RECORD hash: {name}")
        data = read_file(name)
        algorithm, expected = digest.split("=", 1)
        actual = base64.urlsafe_b64encode(hashlib.new(algorithm, data).digest()).rstrip(b"=")
        if actual.decode() != expected or (size and len(data) != int(size)):
            raise ValueError(f"RECORD mismatch: {name}")
        verified.add(name)
    if not verified:
        raise ValueError(f"No hashed package files in RECORD: {required}")
    return verified


def validate(kind, root):
    if kind == "te":
        wheels = list(root.glob("transformer_engine*.whl"))
        if len(wheels) != 1:
            raise ValueError(f"Expected one TE wheel in {root}, found {len(wheels)}")
        with zipfile.ZipFile(wheels[0]) as wheel:
            bad = wheel.testzip()
            if bad:
                raise ValueError(f"Wheel CRC failure: {bad}")
            names = set(wheel.namelist())
            records = [name for name in names if name.endswith(".dist-info/RECORD")]
            if len(records) != 1:
                raise ValueError("Expected one wheel RECORD")
            prefix = records[0].rsplit("/", 1)[0]
            for name in (f"{prefix}/METADATA", f"{prefix}/WHEEL"):
                if not wheel.read(name).strip():
                    raise ValueError(f"Empty wheel metadata: {name}")
            rows = csv.reader(io.StringIO(wheel.read(records[0]).decode()))
            verified = check_record(rows, wheel.read, "transformer_engine/")
            if "transformer_engine/__init__.py" not in verified:
                raise ValueError("Missing verified transformer_engine/__init__.py")
    else:
        records = list(root.glob("megatron_core-*.dist-info/RECORD"))
        if len(records) != 1:
            raise ValueError(f"Expected one Megatron RECORD in {root}")

        def read_file(name):
            path = (root / name).resolve()
            if not path.is_relative_to(root.resolve()):
                raise ValueError(f"RECORD path escapes runtime: {name}")
            return path.read_bytes()

        with records[0].open(newline="") as record:
            verified = check_record(
                csv.reader(record), read_file, "megatron/core/", allow_bytecode=True
            )
        for module in ("", "tensor_parallel/", "transformer/", "pipeline_parallel/"):
            name = f"megatron/core/{module}__init__.py"
            if name not in verified:
                raise ValueError(f"Missing verified module: {name}")
    print(f"Validated {kind} runtime: {root}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("kind", choices=("te", "megatron"))
    parser.add_argument("root", type=Path)
    parser.add_argument("--probe", action="store_true", help="Report valid=false without failing")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    valid = False
    try:
        validate(args.kind, args.root)
        valid = True
    except (
        OSError,
        ValueError,
        KeyError,
        EOFError,
        zipfile.BadZipFile,
        zlib.error,
        csv.Error,
    ) as error:
        level = "warning" if args.probe else "error"
        print(f"::{level}::Invalid {args.kind} runtime: {error}", file=sys.stderr)
    if args.output:
        with args.output.open("a") as output:
            output.write(f"valid={str(valid).lower()}\n")
    return 0 if valid or args.probe else 1


if __name__ == "__main__":
    sys.exit(main())
