# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FlagScale Training Dockerfile for MThreads MUSA Platform

ARG BASE_IMAGE=registry.mthreads.com/mcconline/musa-pytorch-release-public:latest
ARG PKG_MGR=conda
ARG FLAGSCALE_HOME=/opt/flagscale
ARG FLAGSCALE_CONDA=/opt/conda

FROM ${BASE_IMAGE} AS base

ARG FLAGSCALE_HOME
ARG FLAGSCALE_CONDA

ARG PIP_INDEX_URL
ARG PIP_EXTRA_INDEX_URL
ARG UV_INDEX_URL=${PIP_INDEX_URL}
ARG UV_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTPS_PROXY}
ARG no_proxy=${NO_PROXY}

ENV FLAGSCALE_HOME=${FLAGSCALE_HOME}
ENV FLAGSCALE_CONDA=${FLAGSCALE_CONDA}
ENV UV_PROJECT_ENVIRONMENT=${FLAGSCALE_HOME}/venv
ENV VIRTUAL_ENV=${FLAGSCALE_HOME}/venv
ENV FLAGSCALE_DEPS=${FLAGSCALE_HOME}/deps
ENV FLAGSCALE_DOWNLOADS=${FLAGSCALE_HOME}/downloads
ENV UV_HTTP_TIMEOUT=500
ENV UV_INDEX_STRATEGY=unsafe-best-match
ENV UV_LINK_MODE=copy
ENV MPI_HOME=/usr/local/mpi
ENV MUSA_HOME=/usr/local/musa
ENV PATH="${FLAGSCALE_HOME}/venv/bin:${FLAGSCALE_CONDA}/bin:/root/.local/bin:/usr/local/mpi/bin:${MUSA_HOME}/bin:$PATH"
ENV LD_LIBRARY_PATH="${MUSA_HOME}/lib:${MUSA_HOME}/lib64:/usr/local/mpi/lib64:/usr/local/mpi/lib:/usr/local/lib:$LD_LIBRARY_PATH"

COPY tools/install/musa/env.sh /etc/profile.d/flagscale-env.sh

WORKDIR /workspace

FROM base AS deps

ARG PKG_MGR
ARG FLAGSCALE_HOME
ARG FLAGSCALE_CONDA

ARG PIP_INDEX_URL
ARG PIP_EXTRA_INDEX_URL
ARG UV_INDEX_URL
ARG UV_EXTRA_INDEX_URL
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTPS_PROXY}
ARG no_proxy=${NO_PROXY}

ENV PIP_INDEX_URL=${PIP_INDEX_URL}
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_INDEX_URL=${UV_INDEX_URL}
ENV UV_EXTRA_INDEX_URL=${UV_EXTRA_INDEX_URL}

COPY tools/install /workspace/tools/install
COPY requirements /workspace/requirements

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=cache,target=/root/.cache/uv \
    --mount=type=cache,target=/opt/conda/pkgs \
    . /etc/profile.d/flagscale-env.sh && \
    chmod +x /workspace/tools/install/*.sh && \
    chmod +x /workspace/tools/install/utils/*.sh && \
    chmod +x /workspace/tools/install/musa/*.sh && \
    cd /workspace && \
    FLAGSCALE_HOME=${FLAGSCALE_HOME} FLAGSCALE_CONDA=${FLAGSCALE_CONDA} \
    ./tools/install/install.sh --platform musa --task train --pkg-mgr ${PKG_MGR} --no-system && \
    rm -rf /workspace

FROM deps AS dev

CMD ["/bin/bash"]

FROM base AS release

ARG PKG_MGR
ARG FLAGSCALE_HOME
ARG FLAGSCALE_CONDA

ARG PIP_INDEX_URL
ARG PIP_EXTRA_INDEX_URL
ARG UV_INDEX_URL
ARG UV_EXTRA_INDEX_URL
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy=${HTTP_PROXY}
ARG https_proxy=${HTTPS_PROXY}
ARG no_proxy=${NO_PROXY}

ENV PIP_INDEX_URL=${PIP_INDEX_URL}
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ENV UV_INDEX_URL=${UV_INDEX_URL}
ENV UV_EXTRA_INDEX_URL=${UV_EXTRA_INDEX_URL}

COPY tools/install /workspace/tools/install
COPY requirements /workspace/requirements

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=cache,target=/root/.cache/uv \
    --mount=type=cache,target=/opt/conda/pkgs \
    . /etc/profile.d/flagscale-env.sh && \
    chmod +x /workspace/tools/install/*.sh && \
    chmod +x /workspace/tools/install/utils/*.sh && \
    chmod +x /workspace/tools/install/musa/*.sh && \
    cd /workspace && \
    FLAGSCALE_HOME=${FLAGSCALE_HOME} FLAGSCALE_CONDA=${FLAGSCALE_CONDA} \
    ./tools/install/install.sh --platform musa --task train --pkg-mgr ${PKG_MGR} --no-system --no-dev && \
    rm -rf /workspace

CMD ["/bin/bash"]
